### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge 报错

### ISSUE THREAD

**Issue by MIIXNON** [liuyuan-pal/Gen6D#104]
首先非常感谢你们团队的付出。其次我在运行eval.py时，发现程序在迭代几轮之后就会报错，显示numpy.linalg.LinAlgError: SVD did not converge。我修改了相关包的版本，但是错误依旧，请问可以提供一些帮助吗？非常感谢！

/home/b1005/.virtualenvs/test/lib/python3.8/site-packages/torch/nn/functional.py:3060: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
 10%|██████████████████▉                                                                                                                                                                     | 26/252 [00:17<02:35,  1.46it/s]
Traceback (most recent call last):
  File "eval.py", line 162, in <module>
    main(args)
  File "eval.py", line 125, in main
    pose_pr, inter_results = estimator.predict(img, K)
  File "/data/library/Gen6D/Gen6D/estimator.py", line 213, in predict
    pose_pr = self.refiner.refine_que_imgs(que_img, que_K, pose_pr, size=128, ref_num=6, ref_even=True)
  File "/data/library/Gen6D/Gen6D/network/refiner.py", line 336, in refine_que_imgs
    pose_pr = pose_sim_to_pose_rigid(pose_sim, in_pose_warp, que_K_warp, que_K_warp, object_center)
  File "/data/library/Gen6D/Gen6D/utils/pose_utils.py", line 223, in pose_sim_to_pose_rigid
    U, S, V = np.linalg.svd(pose_sim_in_to_que[:3,:3])
  File "<__array_function__ internals>", line 200, in svd
  File "/home/b1005/.virtualenvs/test/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1642, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/b1005/.virtualenvs/test/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

**Comment by liuyuan-pal** [comment]
这里似乎预测的旋转出问题了，不太清楚这里预测出来是啥~

**Comment by MIIXNON** [comment]
感谢您抽空回答我的问题，我使用的是linux系统，今天经过排查发现是显卡驱动的问题，重装之后不进入图形化界面操作程序就可以正常跑通了，再次感谢！
