### ISSUE TITLE
Code error on custom test

### ISSUE THREAD

**Issue by Eric-JH** [liuyuan-pal/Gen6D#25]
The code `img = self.img_norm(imgs)` in `network/detector.py` reports `ValueError: Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = torch.Size([32, 3, 120, 120]).`

**Comment by liuyuan-pal** [comment]
Hi, the given information is not enough for me to locate your problem. You may compare your data with the given `mouse_processed` data to find where the problem is.

**Comment by Eric-JH** [comment]
I followed the instruction in `custom_object.md` to run `predict.py` with given `mouse_processed` data. Then I failed because of the error I mentioned above.  Here is the error infomation indicating the wrong usage of `torchvision.transforms.Normalize` function in `detector.py`
```
Traceback (most recent call last):
  File "/home/jh/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jh/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jh/WD/Gen6D/predict.py", line 97, in <module>
    main(args)
  File "/home/jh/WD/Gen6D/predict.py", line 32, in main
    estimator.build(ref_database, split_type='all')
  File "/home/jh/WD/Gen6D/estimator.py", line 166, in build
    self.detector.load_ref_imgs(ref_imgs[:self.cfg['det_ref_view_num']])
  File "/home/jh/WD/Gen6D/network/detector.py", line 296, in load_ref_imgs
    self.load_impl(ref_imgs)
  File "/home/jh/WD/Gen6D/network/detector.py", line 210, in load_impl
    self.ref_center_feats = self.extract_feats(ref_imgs)
  File "/home/jh/WD/Gen6D/network/detector.py", line 190, in extract_feats
    img = self.img_norm(imgs)
  File "/home/jh/.conda/envs/torch/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 212, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/jh/.conda/envs/torch/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 284, in normalize
    '{}.'.format(tensor.size()))
ValueError: Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = torch.Size([32, 3, 120, 120]).
```

**Comment by liuyuan-pal** [comment]
This seems weird that this normalization is able to act on 4D tensor as state in https://pytorch.org/vision/main/generated/torchvision.transforms.functional.normalize.html#torchvision.transforms.functional.normalize

**Comment by Eric-JH** [comment]
Sry. I didn't notice that my torch version was 1.6. Problem has been solved by updating torch
