### ISSUE TITLE
Custom object : KeyError in database.py get_pose()

### ISSUE THREAD

**Issue by apirrone** [liuyuan-pal/Gen6D#30]
Hello, 

I think I followed quite accurately the instructions for custom objects, but when I try to run `predict.py` like this : 

```
python3 predict.py --cfg configs/gen6d_pretrain.yaml --database custom/pince --video data/custom/video/pince_test.mp4 --resolution 960 --transpose --output data/custom/pince/test --ffmpeg /usr/bin/ffmpeg
```
I get the following error :
```
Traceback (most recent call last):
  File "predict.py", line 99, in <module>
    main(args)
  File "predict.py", line 34, in main
    estimator.build(ref_database, split_type='all')
  File "<...>/Gen6D/estimator.py", line 147, in build
    ref_ids = select_reference_img_ids_fps(database, ref_ids_all, self.cfg['ref_view_num'])
  File "<...>/Gen6D/./utils/database_utils.py", line 115, in select_reference_img_ids_fps
    poses = [database.get_pose(ref_id) for ref_id in ref_ids_all]
  File "<...>/Gen6D/./utils/database_utils.py", line 115, in <listcomp>
    poses = [database.get_pose(ref_id) for ref_id in ref_ids_all]
  File "<...>/Gen6D/dataset/database.py", line 282, in get_pose
    return self.poses[img_id].copy()
```

When I print the keys of `self.poses`, keys '2', '14', '20', and '25' are missing :

```
dict_keys(['0', '1', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '15', '16', '17', '18', '19', '21', '22', '23', '24', '26', '27', '28', '29', '30', '31', '32', '33', '34'])
dict_keys(['0', '1', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '15', '16', '17', '18', '19', '21', '22', '23', '24', '26', '27', '28', '29', '30', '31', '32', '33', '34'])
dict_keys(['0', '1', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '15', '16', '17', '18', '19', '21', '22', '23', '24', '26', '27', '28', '29', '30', '31', '32', '33', '34'])
```

Any ideas why ? 

Thanks !

**Comment by apirrone** [comment]
I started the process all over again on a longer video and I did not get this problem again. Should I keep the issue open if I have the same problem with another video ?

**Comment by liuyuan-pal** [comment]
I'm not sure what happened here, maybe you can keep this open if anyone else encounters a similar problem.

**Comment by hanhanhan666666** [comment]
我也遇到这个问题了，为什么有的索引的pose会缺失啊

**Comment by liuyuan-pal** [comment]
The reason for this issue may be that 
1. you use the COLMAP in windows and manually copy the images into the COLMAP project. 
3. The COLMAP is unable to recover the camera poses of your video.

**Comment by robinupup** [comment]
我也遇到了，请问除了重拍视频外有什么解决办法吗

**Comment by robinupup** [comment]
`    def get_pose(self, img_id):
        if(self.poses.get(img_id) is None):
            return self.poses['0'].copy()
        return self.poses[img_id].copy()`
我使用上述代码在database.py中隔离了此问题，但应该会对最终效果造成影响。

**Comment by robinupup** [comment]
`def get_pose(self, img_id):`
  `if(self.poses.get(img_id) is None):`
      `return self.poses['0'].copy()`
   `return self.poses[img_id].copy()`
我使用上述代码在database.py中隔离了这个问题，但应该会对最终效果造成影响。
