### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by ggamaz** [liuyuan-pal/Gen6D#41]
Hello, first of all, thank you for sharing such excellent work. However, I found some minor problems during operation. First, how much video memory is needed for the graphics card to run this project? When I ran the first project, the video memory was insufficient. In the custom object, colmap showed the following WARNING: No images with matches found in the database. What kind of problem is that? Looking forward to your reply @liuyuan-pal

**Comment by liuyuan-pal** [comment]
Hi, you may first try the provided `mouse` object to check whether your GPU is suitable for Gen6D or not. I did most experiments on a single 1080Ti GPU with 12G memory. For inference only, it does not consume too much memory (2~3G memory should be enough).

**Comment by ggamaz** [comment]
Sorry, I'm new to this, and this is what happens when I run the mouse object, as follows:
WARNING: No images with matches found in the database.

ERROR: failed to create sparse model
Traceback (most recent call last):
File "prepare.py", line 98, in
build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
File "/home/galaxy/Downloads/Gen6D-main/colmap_script.py", line 104, in build_colmap_model_no_pose
run_sfm(colmap_path, sparse_model_path, database_path, image_path)
File "/home/galaxy/Downloads/Gen6D-main/colmap_script.py", line 24, in run_sfm
subprocess.run(cmd, check=True)
The File "/ home/galaxy/miniconda3 / envs/gen6d/lib/python3.8 subprocess. Py", line 516, in the run
raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError:  Command '['/usr/local/bin/colmap', 'mapper', '--database_path', 'data/custom/mouse/colmap/database.db', '--image_path',  'data/custom/mouse/colmap/images', '--output_path', 'data/custom/mouse/colmap/sparse']' returned non-zero exit status 1.
I would appreciate it if you could help me.

**Comment by liuyuan-pal** [comment]
The problem is that COLMAP is unable to generate matches. You may use the COLMAP GUI to visualize the images to see what happened. I think this may relate to the installation of your COLMAP.

**Comment by ggamaz** [comment]
thanks for you reply, I have some problem in installing my colmap.
