### ISSUE TITLE
Inference on custom dataset producing key reference error

### ISSUE THREAD

**Issue by blackHorz** [liuyuan-pal/Gen6D#48]
python predict.py --cfg configs/gen6d_pretrain.yaml --database custom/kappa --video data/custom/video/kappa-test.MOV --resolution 960 --transpose --output data/custom/kappa/test --ffmpeg ffmpeg
/home/fftai/anaconda3/envs/gen6d/lib/python3.7/site-packages/torchvision/models/_utils.py:136: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  f"Using {sequence_to_str(tuple(keyword_only_kwargs.keys()), separate_last='and ')} as positional "
/home/fftai/anaconda3/envs/gen6d/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG11_BN_Weights.IMAGENET1K_V1`. You can also use `weights=VGG11_BN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/fftai/anaconda3/envs/gen6d/lib/python3.7/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
load from detector_pretrain/model_best.pth step 240000
load from selector_pretrain/model_best.pth step 270000
load from refiner_pretrain/model_best.pth step 260000
Traceback (most recent call last):
  File "predict.py", line 97, in <module>
    main(args)
  File "predict.py", line 32, in main
    estimator.build(ref_database, split_type='all')
  File "/home/fftai/working/6D Pose Estimation/Gen6D-main/estimator.py", line 145, in build
    ref_ids = select_reference_img_ids_fps(database, ref_ids_all, self.cfg['ref_view_num'])
  File "/home/fftai/working/6D Pose Estimation/Gen6D-main/utils/database_utils.py", line 115, in select_reference_img_ids_fps
    poses = [database.get_pose(ref_id) for ref_id in ref_ids_all]
  File "/home/fftai/working/6D Pose Estimation/Gen6D-main/utils/database_utils.py", line 115, in <listcomp>
    poses = [database.get_pose(ref_id) for ref_id in ref_ids_all]
  File "/home/fftai/working/6D Pose Estimation/Gen6D-main/dataset/database.py", line 290, in get_pose

**Comment by blackHorz** [comment]
I looked further in the database.py code and found out self.pose has all the keys but not '49'. Does this mean it is coming from sfm? What can go wrong there?
