### ISSUE TITLE
colmap

### ISSUE THREAD

**Issue by 1gjjuser1** [liuyuan-pal/Gen6D#56]
I run this command on colab !python prepare.py --action sfm --database_name custom/mouse --colmap /content/drive/MyDrive/colab/COLMAP-3.6-windows-cuda/bin/colmap.exe

But an error was reported:

Traceback (most recent call last):
   File "prepare.py", line 98, in <module>
     build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
   File "/content/drive/MyDrive/gen6D/colmap_script.py", line 99, in build_colmap_model_no_pose
     extract_and_match_sift(colmap_path, database_path, image_path)
   File "/content/drive/MyDrive/gen6D/colmap_script.py", line 63, in extract_and_match_sift
     subprocess. run(cmd, check=True)
   File "/usr/lib/python3.8/subprocess.py", line 493, in run
     with Popen(*popenargs, **kwargs) as process:
   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
     raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/content/drive/MyDrive/colab/COLMAP-3.6-windows-cuda/bin/colmap.exe'

Can you help me, thank you

**Comment by weidu3** [comment]
I encountered the same problem as you, how did you solve it?

**Comment by omega-cw** [comment]
> 

Hi, I also meet the same problem. Did you solve it?

**Comment by juicyjung** [comment]
Hi, I also meet the same problem. Did you solve it?

**Comment by HomeworldL** [comment]
Hi, I also meet the same problem. Maybe I use colmap in Ubuntu (22.04), but you may use it in Windows.

**Comment by douyizi** [comment]
Hi, I also meet the same problem. Did you solve it?

**Comment by Chen-Yulin** [comment]
I used colmap 3.9.1 windows version and met similar problem. I solved the problem by using 3.7 version
