### ISSUE TITLE
.ply file cannot be generated

### ISSUE THREAD

**Issue by 1gjjuser1** [liuyuan-pal/Gen6D#57]
I am on the local win10 system, run this command python prepare.py --action sfm --database_name custom/mouse --colmap F:\1AMy_source\Graduate student\transparent object\mine\Gen6D\COLMAP-3.8-windows-no -cuda\COLMAP-3.8-windows-no-cuda\bin\colmap.exe

The colmap/images/ and database.db files can be generated, but the .ply file cannot be generated, and the error message is as follows:
D:\Anaconda\envs\gen\python.exe "F:\1AMy_source\Graduate student\transparent object\mine\Gen6D\code\prepare.py" --action sfm --database_name custom/mouse --colmap "F: \1AMy_source\Graduate\student\transparent object\mine\Gen6D\COLMAP-3.8-windows-no-cuda\COLMAP-3.8-windows-no-cuda\bin\colmap.exe"
��Ŀ¼����ļ� data\custom\mouse �Ѿ����ڡ�
����: data\custom\mouse ʱ����
Traceback (most recent call last):
   File "F:\1AMy_source\Graduate student\transparent object\mine\Gen6D\code\prepare.py", line 98, in <module>
     build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
   File "F:\1AMy_source\Graduate student\transparent object\mine\Gen6D\code\colmap_script.py", line 99, in build_colmap_model_no_pose
     extract_and_match_sift(colmap_path, database_path, image_path)
   File "F:\1AMy_source\Graduate student\transparent object\mine\Gen6D\code\colmap_script.py", line 63, in extract_and_match_sift
     subprocess. run(cmd, check=True)
   File "D:\Anaconda\envs\gen\lib\subprocess.py", line 493, in run
     with Popen(*popenargs, **kwargs) as process:
   File "D:\Anaconda\envs\gen\lib\subprocess.py", line 858, in __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
   File "D:\Anaconda\envs\gen\lib\subprocess.py", line 1311, in _execute_child
     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified.

Process finished with exit code 1

I have been searching for a long time but I can't find where the problem is, can you help me, thank you

**Comment by liuyuan-pal** [comment]
This seems to be related to your COLMAP installation. You may try some other examples to check whether your COLMAP is working or not. I suggest to re-install COLMAP according to the instructions on COLMAP homepage.
