### ISSUE TITLE
训练中途报错ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by baldman12** [liuyuan-pal/Gen6D#69]
在训练detector和selector时会报错以下是详细信息：
File "/media/dj/F054ABE054ABA7B4/code/py/6D/Gen6D-main/train_model.py", line 11, in <module>
    trainer.run()
  File "/media/dj/F054ABE054ABA7B4/code/py/6D/Gen6D-main/train/trainer.py", line 111, in run
    train_data = next(train_iter)
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dj/conda/envs/pyotrch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/dj/F054ABE054ABA7B4/code/py/6D/Gen6D-main/dataset/train_dataset.py", line 992, in __getitem__
    database, que_ids = self._select_query(index)
  File "/media/dj/F054ABE054ABA7B4/code/py/6D/Gen6D-main/dataset/train_dataset.py", line 247, in _select_query
    database = self.name2database[np.random.choice(names)]
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

好像是集合为空的问题，请问应该如何解决。谢谢

**Comment by liuyuan-pal** [comment]
你要不看看是不是漏了其中哪个数据集，看看这个names是不是空的~

**Comment by baldman12** [comment]
Gen6D
|-- data
    |-- GenMOP
        |-- chair 
            ...
    |-- LINEMOD
        |-- cat 
            ...
    |-- shapenet
        |-- shapenet_cache
        |-- shapenet_render
        |-- shapenet_render_v1.pkl
    |-- co3d_256_512
        |-- apple
            ...
    |-- google_scanned_objects
        |-- 06K3jXvzqIM
            ...
    |-- coco
        |-- train2017 


我是按照这样格式来布置数据集的，是否还需要某些数据集。而且这个是训练到一半会报错，有时候是第3次 有时候是第14次。

**Comment by baldman12** [comment]
|-- data
     |-- GenMOP
          |-- chair 
            ...
    |-- LINEMOD
        |-- cat 
             ...
    |-- shapenet
        |-- shapenet_cache
        |-- shapenet_render
        |-- shapenet_render_v1.pkl
    |-- co3d_256_512
        |-- apple
            ...
    |-- google_scanned_objects
        |-- 06K3jXvzqIM
            ...
    |-- coco
        |-- train2017                 我是这样布置的，是否还需要其他数据集。并且这个报错是训练中途报错，有时是第3次有时是第15次

**Comment by EvdoTheo** [comment]
Hello @baldman12, I had the same problem while I was training the detector and I solved this issue by modifying the value  **use_database_sample_prob** in the config file from **true** to **false**. @liuyuan-pal can you explain the use of this value? Thank you!

**Comment by Oskris** [comment]
@baldman12  您好，请问可以给我参考一下你的 co3d、google scanned objects和shapeNet数据集吗，我直接下载的数据集组织形式并没有像作者的这样

**Comment by Tony001123** [comment]
> Hello [@baldman12](https://github.com/baldman12), I had the same problem while I was training the detector and I solved this issue by modifying the value **use_database_sample_prob** in the config file from **true** to **false**. [@liuyuan-pal](https://github.com/liuyuan-pal) can you explain the use of this value? Thank you!

I met the same question as you. I solved it by setting use_database_sample_prob as false and I did not change other settings. Then I tried to train Gen6d. I eval my own trained weight when I fished three steps as writer listed.The results of add-0.1s and prj-0.5 is not as good as pre-trained of writer. Bro ,Have you met the same question?  
linemod/cat gen6d_pretrain       add-0.1d 0.6028 prj-5 0.9621  
linemod/cat gen6d_train          add-0.1d 0.3703 prj-5 0.8713

**Comment by Tony001123** [comment]
I think there is something wrong with google-scanned-object dataset of the shared zip. I trained the models(setting use_database_sample_prob=true) and I print “database_name”.When database_name is google-scanned-object it shows that the database_name is empty and this error occur. Could someone show me the character of the google-scanned-object or how to solve this problems.
