### ISSUE TITLE
获取验证数据时报错FileNotFoundError: [Errno 2] No such file or directory: 'data/val/det/linemod/cat/detector_train.pkl'

### ISSUE THREAD

**Issue by Reisenya** [liuyuan-pal/Gen6D#72]
输入python prepare.py --action gen_val_set --estimator_cfg configs/gen6d_train.yaml --que_database linemod/cat --que_split linemod_val --ref_database linemod/cat --ref_split linemod_val后报错，内容如下：
命令语法不正确。
Traceback (most recent call last):
  File "prepare.py", line 100, in <module>
    prepare_validation_set(args.ref_database,args.que_database,args.ref_split,args.que_split,args.estimator_cfg)
  File "prepare.py", line 70, in prepare_validation_set
    save_pickle(img_id2det_info,f'data/val/det/{que_database_name}/{estimator.detector.cfg["name"]}.pkl')
  File "F:\Gen6D\utils\base_utils.py", line 33, in save_pickle
    with open(pkl_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/val/det/linemod/cat/detector_train.pkl'
不知道是哪里出了问题，麻烦您提点一下，谢谢！

**Comment by liuyuan-pal** [comment]
`data/val/det/linemod/cat`这个路径不存在

**Comment by Reisenya** [comment]
这个路径和pkl文件没有成功生成出来是什么原因呢？我在训练detector和selector时将优化器的total step缩短了一些，请问有可能是因为这个吗？

**Comment by liuyuan-pal** [comment]
这个路径和训练轮次没有关系，应该不是这个原因，具体原因我也不清楚
