### ISSUE TITLE
custom object：关于COLMAP

### ISSUE THREAD

**Issue by HarrisonWells** [liuyuan-pal/Gen6D#75]
Windows系统，安装好了colmap，但是只有bat文件可以运行，exe文件无法运行，提示缺少很多dll文件。运行python prepare.py --action sfm --database_name custom/mouse --colmap <path-to-your-colmap-exe>时，报错
Traceback (most recent call last):
  File "D:\N\组会准备\无人车建模\Gen6D-main\prepare.py", line 98, in <module>
    build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
  File "D:\N\组会准备\无人车建模\Gen6D-main\colmap_script.py", line 99, in build_colmap_model_no_pose
    extract_and_match_sift(colmap_path, database_path, image_path)
  File "D:\N\组会准备\无人车建模\Gen6D-main\colmap_script.py", line 63, in extract_and_match_sift
    subprocess.run(cmd, check=True)
  File "D:\Anaconda\envs\yolov7\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\envs\yolov7\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda\envs\yolov7\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
**PermissionError: [WinError 5] 拒绝访问。**
请问该怎么解决呢？

**Comment by JustC0deIt** [comment]
你好，这个问题你解决了吗，我也遇到了同样的问题，并且没有找到解决方法

**Comment by HarrisonWells** [comment]
不好意思，我当时解决不了就放弃了 @JustC0deIt
