### ISSUE TITLE
Dense stereo reconstruction requires CUDA, which is not available on your system.

### ISSUE THREAD

**Issue by juicyjung** [liuyuan-pal/Gen6D#85]
Hi, Thank you for the nice code.

When I just tried to make custom object.

4. Run COLMAP SfM to recover camera poses with below command.

`python prepare.py --action sfm --database_name custom/target --colmap colmap/build/src/exe/colmap`

I got this error after running long time.

> ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.
> Traceback (most recent call last):
>   File "prepare.py", line 98, in <module>
>     build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
>   File "/home/gachongpu/Downloads/Gen6D/colmap_script.py", line 105, in build_colmap_model_no_pose
>     run_patch_match(colmap_path, sparse_model_path / '0', image_path, dense_model_path)
>   File "/home/gachongpu/Downloads/Gen6D/colmap_script.py", line 35, in run_patch_match
>     subprocess.run(cmd, check=True)
>   File "/home/gachongpu/anaconda3/envs/6d/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['colmap/build/src/exe/colmap', 'patch_match_stereo', '--workspace_path', 'data/custom/target/colmap/dense']' returned non-zero exit status 1.

My cuda is okay. torch.cuda.is_available() : True

What happened?

anyone who has same error with me?

**Comment by liuyuan-pal** [comment]
Hi, it seems that you need to install COLMAP with CUDA. https://colmap.github.io/install.html
You need to compile with CUDA support.
